version: "3.7"
x-quorum-def: &quorum-def
  restart: "on-failure"
  image: quorumengineering/quorum:latest
  entrypoint: /start.sh
  environment:
    - QUORUM_CONSENSUS=raft

x-tx-manager-def: &tx-manager-def
  restart: "no"
  image: quorumengineering/tessera:latest
  entrypoint: /start.sh

services:
  tessera1:
    <<: *tx-manager-def
    container_name: tessera_1
    volumes:
      - ./Tessera-0/start.sh:/start.sh
      - ./Tessera-0/config.json:/qdata/tm/config.json
      - ./Tessera-0/tessera1.key:/qdata/tm/tm.key
      - ./Tessera-0/tessera1.pub:/qdata/tm/tm.pub
    expose:
      - "21010"
      - "9001"
      - "9005"
    ports:
      - "21010:21010"
      - "9001:9001"
      - "9005:9005"

    networks:
      quorum-net:
        ipv4_address: 172.15.0.5

  tessera2:
    <<: *tx-manager-def
    container_name: tessera_2
    volumes:
      - ./Tessera-1/start.sh:/start.sh
      - ./Tessera-1/config.json:/qdata/tm/config.json
      - ./Tessera-1/tessera1.key:/qdata/tm/tm.key
      - ./Tessera-1/tessera1.pub:/qdata/tm/tm.pub
    expose:
      - "21011"
      - "9003"
      - "9006"

    ports:
      - "21011:21011"
      - "9003:9003"
      - "9006:9006"

    networks:
      quorum-net:
        ipv4_address: 172.15.0.6

  node0:
    <<: *quorum-def
    container_name: node0_1
    volumes:
      - ./node0/private-contract.js:/private-contract.js
      - ./node0/start.sh:/start.sh
      - ./genesis.json:/qdata/dd/genesis.json
      - ./node0/datadir/nodekey:/qdata/dd/nodekey
      - ./node0/datadir/static-nodes.json:/qdata/dd/static-nodes.json
    ports:
      - "22005:22005"
      - "22010:22010"
    networks:
      quorum-net:
        ipv4_address: 172.15.0.10

  node1:
    <<: *quorum-def
    container_name: node0_2
    volumes:
      - ./node1/start.sh:/start.sh
      - ./genesis.json:/qdata/dd/genesis.json
      - ./node1/datadir/nodekey:/qdata/dd/nodekey
      - ./node1/datadir/static-nodes.json:/qdata/dd/static-nodes.json

    ports:
      - "22006:22006"
      - "22011:22011"

    networks:
      quorum-net:
        ipv4_address: 172.15.0.11
  node2:
    <<: *quorum-def
    container_name: node0_3
    volumes:
      - ./node2/start.sh:/start.sh
      - ./genesis.json:/qdata/dd/genesis.json
      - ./node2/datadir/nodekey:/qdata/dd/nodekey
      - ./node2/datadir/static-nodes.json:/qdata/dd/static-nodes.json

    ports:
      - "22007:22007"
      - "22012:22012"

    networks:
      quorum-net:
        ipv4_address: 172.15.0.12

  explorer:
    image: consensys/quorum-explorer:latest
    volumes:
      - ./config.json:/app/config.json
      - ./.env.production:/app/.env.production
    ports:
      - 25000:25000/tcp

networks:
  quorum-net:
    name: quorum-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.15.0.0/16
